Added event handler for cauldron water level modification to prevent untrusted players interacting with a plot
IntellectualSites/PlotSquared pull request #3035
Opened 2021-05-17 19:19 UTC by ThisIsIPat

Changes in the water level of a cauldron are now cancelled unless a player modifies it and that player has permissions to interact with the plot

Valid permissions:
``plots.admin.interact.road``
``plots.admin.interact.unowned``
``plots.admin.interact.other``
``Player is trusted or owner of the plot``

**Fixes https://github.com/IntellectualSites/PlotSquared/issues/3034**

2021-05-17 19:22 UTC, ThisIsIPat commented
Note: It still extinguishes the player. It merely doesn't change the water level.

Another note: The water level is now also not modified by rain or, since 1.17, dripstone. This could possibly be implemented via a flag. If requested, the PR will be modified so that rain and dripstone will still modify a cauldrons water level.

2021-05-17 19:25 UTC, NotMyFault requested changes

2021-05-17 19:25 UTC, NotMyFault commented on Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java
> +            Player player = (Player) entity;
```suggestion
        if (entity instanceof Player player) {
```

2021-05-17 19:28 UTC, NotMyFault commented
> Note: It still extinguishes the player. It merely doesn't change the water level.

Afaik the enum CauldronLevelChangeEvent.ChangeReason takes an extinguish cause determining whether the entity should be extinguished or not.

2021-05-17 19:38 UTC, ThisIsIPat commented
Should cauldron modification by rain be disabled by default?

2021-05-17 19:40 UTC, NotMyFault commented
> Should cauldron modification by rain be disabled by default?

I'd enable it. We don't cancel too many natural events on default if not really necessary, see liquid flow flags e.g.

2021-05-17 20:31 UTC, NotMyFault approved these changes
Thanks for the pr (again)!

2021-05-17 21:28 UTC, ThisIsIPat commented
@NotMyFault Modified event handling so the event represents being cancelled by PlotSquared properly (Instead of having the new cauldron water level be the old one).

Requesting re-review.

2021-05-18 09:53 UTC, NotMyFault approved these changes

2021-05-18 19:20 UTC, SirYwell approved these changes

2021-05-18 19:23 UTC, merged