feat: re-add aggregated javadocs task
IntellectualSites/PlotSquared pull request #3077
Opened 2021-06-01 15:38 UTC by Proximyst

I only a week late.
This will generate the aggregated docs to `docs/javadoc/PlotSquared`, while per-project still go to `docs/javadoc/PlotSquared-${module}`.

---

This was removed by IntellectualSites/PlotSquared#2922.
Closes IntellectualSites/PlotSquared#3037.

Signed-off-by: Mariell Hoversholm <proximyst@proximyst.com>

2021-06-01 16:13 UTC, NotMyFault approved these changes
Thanks for the contribution!

2021-06-02 18:08 UTC, SirYwell requested changes

2021-06-02 18:08 UTC, SirYwell commented on Bukkit/build.gradle.kts
> +        opt.links("https://papermc.io/javadocs/paper/1.16")
It would probably make sense to link the WorldEdit docs too (https://docs.enginehub.org/javadoc/com.sk89q.worldedit/worldedit-core/7.2.0/)

2021-06-02 21:25 UTC, SirYwell approved these changes

2021-06-02 21:26 UTC, merged