Fix index out of bounds for '/p h'
IntellectualSites/PlotSquared pull request #3173
Opened 2021-07-22 14:00 UTC by traksag

## Overview

Running `/p h n` for `n <= 0` throws an index out of bounds exception. You may need to have at least one plot for the exception to be thrown.

## Description

The only change is that we check for the lower bound of 1 on the `page` variable.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v6/CONTRIBUTING.md)

2021-07-22 14:54 UTC, NotMyFault approved these changes
LGTM, but this doesn't cover tab completing of negative inputs.

2021-07-23 08:30 UTC, dordsor21 requested changes
Please address conflicts

2021-07-23 14:31 UTC, traksag commented
Done

2021-07-23 14:33 UTC, dordsor21 approved these changes

2021-07-23 14:33 UTC, merged