Small visit command fixes
IntellectualSites/PlotSquared pull request #3177
Opened 2021-07-22 20:22 UTC by traksag

## Overview

Fixes a couple of issues with the plot visit command.

## Description

This issues fixed are:
- No usage message is sent when you enter more than 3 arguments. A usage message is sent when you use too many arguments for the plot home command.
- You don't get an error message when the 'page' number you input is out of bounds.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v6/CONTRIBUTING.md)

2021-07-22 20:28 UTC, NotMyFault approved these changes

2021-07-23 08:31 UTC, dordsor21 requested changes
Please address conflicts

2021-07-23 14:31 UTC, traksag commented
Done

2021-07-23 14:34 UTC, dordsor21 approved these changes

2021-07-23 14:34 UTC, merged