Slightly change how flag permissions are handled
IntellectualSites/PlotSquared pull request #3201
Opened 2021-08-08 14:26 UTC by dordsor21

- Some flags should not check for a permission "value", mainly string flags
- Add a default true method for asking a flag if it requires a "valued" permission
- Add "keyed" permissions, where we would only expect certain values from a permission, allowing for the "*" modifer to make sense
- Flag permissions without the ".*" make sense to be given to players in the permpack (Fixes #3158)
- Fixes #3151

2021-08-08 15:17 UTC, NotMyFault commented
You mentioned #3158 as fixed, but I still get the same messages trak reported.

2021-08-08 15:18 UTC, dordsor21 commented
> You mentioned #3158 as fixed, but I still get the same messages trak reported.

I managed to completely miss what the report was about... I fixed that the basic flag permpack didn't allow you to remove flags

2021-08-08 16:00 UTC, NotMyFault requested changes

2021-08-08 19:57 UTC, NotMyFault approved these changes

2021-08-14 13:05 UTC, SirYwell approved these changes

2021-08-14 13:13 UTC, merged