Refactor: Replace Rörledning with Cloud-Services
IntellectualSites/PlotSquared pull request #3409
Opened 2021-12-29 15:33 UTC by Citymonstret

Cloud-Services is actually maintained, as opposed to Rörledning. Furthermore, Rörledning is available through Maven Central, whereas rörledning isn't.

This is a semi-breaking change, but because we relocate, it might be fine? Either way, this is a necessary change.

2021-12-29 17:05 UTC, NotMyFault requested changes
Diff looks good so far, but creating a plot world fails https://paste.gg/p/anonymous/1db73e2ca9e64e11994f01c728397cc3

2021-12-30 12:36 UTC, NotMyFault approved these changes
Concerns have been addressed in https://github.com/IntellectualSites/PlotSquared/pull/3409/commits/fc60ca89c2857ad36ff07eb483223f78beef2cfd

2021-12-30 16:08 UTC, dordsor21 approved these changes

2021-12-30 16:11 UTC, NotMyFault commented
We may merge it in ~24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2021-12-31 14:49 UTC, merged