Fix: use portal corners to test for event cancellation as entity can be null
IntellectualSites/PlotSquared pull request #3417
Opened 2021-12-30 16:50 UTC by dordsor21

Fixes #3367

2021-12-30 17:19 UTC, NotMyFault approved these changes

2022-01-04 09:33 UTC, SirYwell requested changes

2022-01-04 13:29 UTC, dordsor21 commented on Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java
> +        for (Location location : new HashSet<>(Arrays.asList( // Use HashSet to lazily avoid duplicate locations
yes

2022-01-04 13:55 UTC, SirYwell approved these changes

2022-01-04 14:18 UTC, NotMyFault commented
We may merge it in ~24 hours if there is no negative feedback, as per the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2022-01-04 14:43 UTC, dordsor21 commented
/rebase

2022-01-05 20:21 UTC, merged