feat: unknown owner(s) for plot expiry
IntellectualSites/PlotSquared pull request #3452
Opened 2022-01-13 22:11 UTC by PierreSchwang

## Overview

## Description
Add's a config option for expiry tasks to respect unknown players in bukkits player database.
Expiry tasks now starts **after** plot areas are loaded.

Adresses https://github.com/IntellectualSites/PlotSquared/issues/3006, at least for specific users. Probably not a fix.

Couldn't test the changes yet because of issues with Fawe + WNA

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [ ] I tested my changes and approved their functionality.
- [ ] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

2022-01-15 20:57 UTC, PierreSchwang commented
/rebase

2022-01-16 22:04 UTC, PierreSchwang commented
Waiting for test results by @iLemon - but worked so far on my testing. therefor opening the PR

2022-01-17 00:27 UTC, PierreSchwang commented
/rebase

2022-01-17 11:05 UTC, NotMyFault commented
/rebase

2022-01-17 14:05 UTC, dordsor21 commented
lgtm as is, will wait for confirmation though as above

2022-01-19 20:00 UTC, iLemon commented
I can confirm that plot expiry works now. The calibration and threshold settings seem broken & confusing but we're still investigating that as it's a separate issue.

2022-01-19 20:23 UTC, NotMyFault requested changes

2022-01-19 20:23 UTC, NotMyFault commented on Core/src/main/java/com/plotsquared/core/configuration/Settings.java
> +        public boolean DELETE_FOR_UNKNOWN_OWNER = false;
I'd rather name it `delete if owner is unknown`, the `for` reads a bit weird.

2022-01-19 20:23 UTC, NotMyFault commented on Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
>                  long start = System.currentTimeMillis();
Can get a rid of this.

2022-01-19 20:23 UTC, NotMyFault commented on Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java
> +     * @param shouldDeleteUnknownOwner true if an unknown player should be counted as never online
```suggestion
     * @param shouldDeleteUnknownOwner {@code true} if an unknown player should be counted as never online
```

2022-01-19 20:23 UTC, NotMyFault commented on Core/src/main/java/com/plotsquared/core/plot/expiration/ExpiryTask.java
> +    public boolean shouldDeleteForUnknownOwner() {
Not really API, but having a `@since` here may be handy in the future.

2022-01-19 21:24 UTC, NotMyFault approved these changes

2022-01-21 19:07 UTC, NotMyFault commented
Conflicted.

2022-01-22 12:31 UTC, dordsor21 approved these changes

2022-01-22 12:36 UTC, NotMyFault commented
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2022-01-23 09:44 UTC, merged