Fix shulkers teleporting on the road
IntellectualSites/PlotSquared pull request #3501
Opened 2022-02-09 18:24 UTC by NotMyFault

## Overview

Fixes https://github.com/IntellectualSites/PlotSquared/issues/3491

## Description

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [X] Changelog entries in the PR title are correct
- [X] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

2022-02-10 12:09 UTC, PierreSchwang reviewed
Looks good so far, but wouldn't it be better to set a new location inside the plot instead of cancelling the whole event?

2022-02-10 12:14 UTC, NotMyFault commented
> Looks good so far, but wouldn't it be better to set a new location inside the plot instead of cancelling the whole event?

The teleport to a block that is not within the plot is cancelled, which leads to the shulker searching for a new location inside the plot.

2022-02-11 17:51 UTC, PierreSchwang approved these changes

2022-02-13 00:06 UTC, yannicklamprecht requested changes
Just some inconsistent variable naming I stumbled over.

2022-02-13 00:06 UTC, yannicklamprecht commented on Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
> +        Plot plot = area.getOwnedPlot(toLocLocation);
I would rename it to plotTo, to be consistent.

2022-02-13 00:06 UTC, yannicklamprecht commented on Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java
> +        PlotArea area = toLocLocation.getPlotArea();
toArea for consistency.

2022-02-13 09:54 UTC, yannicklamprecht approved these changes

2022-02-15 15:05 UTC, dordsor21 approved these changes

2022-02-15 15:20 UTC, NotMyFault commented
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2022-02-16 12:48 UTC, merged