Only show visible players in `/plot near`
IntellectualSites/PlotSquared pull request #3819
Opened 2022-10-01 19:56 UTC by PierreSchwang

## Overview
Fixes #3800

## Description
Checks for the visibility when running `/plot near` (respects "vanish" plugins etc)

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2022-10-02 12:03 UTC, NotMyFault approved these changes
Untested, but looks reasonable.

2022-10-02 13:45 UTC, SirYwell requested changes

2022-10-02 13:45 UTC, SirYwell commented on Core/src/main/java/com/plotsquared/core/plot/Plot.java
> +    public @NonNull List<PlotPlayer<?>> getPlayersInPlotVisible(@NonNull PlotPlayer<?> executor) {
Not sure if a public method in `Plot` is worth it. I'd prefer to have a (private) method in the command as long as it's only used there.

2022-10-02 13:45 UTC, SirYwell commented on Core/src/main/java/com/plotsquared/core/plot/Plot.java
> +        return getPlayersInPlot().stream().filter(executor::canSee).collect(Collectors.toList());
```suggestion
        return getPlayersInPlot().stream().filter(executor::canSee).toList();
```

2022-10-03 18:28 UTC, SirYwell approved these changes

2022-10-03 19:50 UTC, merged