Officially deprecated BukkitPlayer#BukkitPlayer()
IntellectualSites/PlotSquared pull request #3922
Opened 2023-01-10 10:08 UTC by NotMyFault

According to the javadocs, this method is already discouraged. Let's make it official.

2023-01-11 16:47 UTC, dordsor21 approved these changes

2023-01-11 16:59 UTC, SirYwell requested changes
The comment basically applies to the other ctor too. However, these ctors are requiredn in PlotSquared so we can't just remove them. In best case, there wouldn't be public ctors for this class, but from a quick look there's no nice solution to avoid that.

2023-01-11 17:17 UTC, NotMyFault commented
> so we can't just remove them

Nobody said they will be removed? Take a look at my javadoc comment.

2023-01-11 17:28 UTC, SirYwell commented
Well, change their visibility, whatever. Both are used in PlotSquared code right now, and a more restricted visibility isn't possible with the current structure.

Also, this causes a new warning in the class where this constructor is used. It should be suppressed if it does not apply or the code should be changed to not use a deprecated method.

2023-01-11 17:33 UTC, NotMyFault commented
> a more restricted visibility isn't possible with the current structure.

I had no issue weakening the access level at compile time.

2023-01-11 17:35 UTC, SirYwell commented
I see, I misread the code. Still, the deprecation should apply to the other constructor aswell and the warnings should be suppressed in BukkitPlayerManager.

2023-01-12 09:01 UTC, SirYwell approved these changes

2023-01-12 09:03 UTC, merged