Record-inize methods
IntellectualSites/PlotSquared pull request #3976
Opened 2023-03-04 11:57 UTC by NotMyFault

This is an alternative approach to https://github.com/IntellectualSites/PlotSquared/pull/3942/, without deprecations in v6 because the methods are subject to removal anyway. Therefore, deprecating them pointing to the drop-in methods is a bit _point_less.

I don't plan to spend more time implementing static accessors in v6 at this point.

2023-03-04 22:34 UTC, NotMyFault commented
@SirYwell Your favorite checkstyle has been applied.

2023-03-05 07:26 UTC, SirYwell requested changes
There are a few places were we can probably remove even more code, but looks nice!

2023-03-05 07:26 UTC, SirYwell commented on Core/src/main/java/com/plotsquared/core/plot/BlockBucket.java
> +            public boolean equals(final Object o) {
I think we can fully remove the equals and hashCode methods here

2023-03-05 07:26 UTC, SirYwell commented on Core/src/main/java/com/plotsquared/core/services/plots/AutoQuery.java
> +    public AutoQuery(
Annotations can be added to the record components, and the `@param` tag is allowed at the record header too. Can we remove the constructor as well as the methods?

2023-03-05 07:26 UTC, SirYwell commented on Core/src/main/java/com/plotsquared/core/uuid/UUIDMapping.java
>      public boolean equals(final Object o) {
This method can be dropped too I guess?

2023-03-05 09:04 UTC, SirYwell approved these changes

2023-03-05 09:07 UTC, merged