Fixes many database issues and add scale for bigger propose
IntellectualSites/PlotSquared pull request #4075
Opened 2023-06-13 18:59 UTC by TheMeinerLP

## Overview

## Description
Currently our server get some connection lost issues or resets and plotsqured will after that be down.
This pr fixes generally very old code from PS² and is a modern way too go.

## Disclaimer
**This PR breaks other plugin compatibilty** 

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

2023-06-18 16:02 UTC, NotMyFault requested changes
Needs some discussion

2023-06-18 18:45 UTC, TheMeinerLP commented
> Up front, this PR can't make it into v7's general availability release.
> 
> To maintain a proper deprecation cycle, public methods you want to see gone must be deprecated beforehand, providing methods to migrate to. HikariCP isn't relocated, either.
> 
> I recommend reworking this PR to provide a smooth introduction, rather than a hard cut.

I made these changes as new storage adapter for prevent breaking changes ok ?

2023-06-18 19:00 UTC, NotMyFault commented
> > Up front, this PR can't make it into v7's general availability release.
> > To maintain a proper deprecation cycle, public methods you want to see gone must be deprecated beforehand, providing methods to migrate to. HikariCP isn't relocated, either.
> > I recommend reworking this PR to provide a smooth introduction, rather than a hard cut.
> 
> I made these changes as new storage adapter for prevent breaking changes ok ?

No such change has been pushed.

2025-09-08 08:09 UTC, TheMeinerLP commented
Closed because: https://github.com/IntellectualSites/PlotSquared/pull/4748

2025-09-08 08:09 UTC, closed without merging