Replace deprecated ageable with breedable
IntellectualSites/PlotSquared pull request #4193
Opened 2023-10-01 12:18 UTC by TheMeinerLP

## Overview
Replace depreacted ageable.

Fixes #4164 

## Description

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right sidX)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

2023-10-01 12:20 UTC, dordsor21 commented
Missing since tags on the deprecated and the new methods

2023-10-01 12:57 UTC, NotMyFault reviewed
since's should be TODO, and deprecations have to have since's too.

2023-10-04 07:55 UTC, TheMeinerLP commented
> since's should be TODO, and deprecations have to have since's too.

Is there a useful adapter ?

2023-10-04 08:43 UTC, NotMyFault commented
> > since's should be TODO, and deprecations have to have since's too.
> 
> Is there a useful example ?

https://www.baeldung.com/java-deprecated#optional-attributes

2023-10-05 17:58 UTC, SirYwell requested changes

2023-10-05 17:58 UTC, SirYwell commented on Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java
> +    public void storeBreedable(Breedable breedable) {
Can be private

2023-10-05 19:40 UTC, SirYwell approved these changes

2023-10-07 18:15 UTC, NotMyFault approved these changes
Thanks!

2023-10-07 18:15 UTC, merged