PostPlotClearEvent added
IntellectualSites/PlotSquared pull request #4268
Opened 2023-12-14 21:48 UTC by David-M-GitHub

## Overview
PostPlotClearEvent added

2023-12-14 21:52 UTC, dordsor21 commented
I think it could be worth making this a player event, as the clearing player could be a moderator/admin, not just the plot owner for example

2023-12-14 22:05 UTC, PierreSchwang requested changes
And don't delete the checklist. It's there for a reason (e.g. describing the usage of the since annotation)

2023-12-14 22:05 UTC, PierreSchwang commented on Core/src/main/java/com/plotsquared/core/events/post/PostPlotClearEvent.java
> + */
`@since TODO`

2023-12-14 22:05 UTC, PierreSchwang commented on Core/src/main/java/com/plotsquared/core/events/post/PostPlotClearEvent.java
> +public class PostPlotClearEvent extends PlotEvent implements CancellablePlotEvent {
No reason to make this event cancellable. There is nothing to cancel.

2023-12-14 22:05 UTC, PierreSchwang commented on Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
> +        PlotClearEvent event = new PlotClearEvent(plot);
Wrong event called.

2023-12-14 22:05 UTC, PierreSchwang commented on Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
> +    public PlotClearEvent callPostClear(Plot plot) {
Wrong Event returned

2023-12-14 22:05 UTC, PierreSchwang commented on Core/src/main/java/com/plotsquared/core/util/EventDispatcher.java
> +    public PlotClearEvent callPostClear(Plot plot) {
Rather name it `callPostPlotClear`

2023-12-16 18:18 UTC, dordsor21 commented on Core/src/main/java/com/plotsquared/core/events/post/PostPlotClearEvent.java
> + * @since 7.2.1
This should be `TODO` as we have a task that will go through and replace them automagically

2023-12-16 18:22 UTC, dordsor21 commented
I would still like this to be extend PlotPlayerEvent as the player executing the clear would be useful to know

2023-12-20 15:03 UTC, dordsor21 commented on Core/src/main/java/com/plotsquared/core/events/post/PostPlotClearEvent.java
> +    public PlotPlayer<?> getPlotPlayer() {
These methods do not need to be here, no need to add extra methods that the API user can do themselves

2023-12-26 15:25 UTC, dordsor21 commented on Core/src/main/java/com/plotsquared/core/events/post/PostPlotClearEvent.java
> +    public PlotId getPlotId() {
These two methods should still not be here tbh

2024-01-11 23:39 UTC, PierreSchwang approved these changes

2024-01-12 08:35 UTC, NotMyFault approved these changes

2024-01-21 14:22 UTC, merged